image: Visual Studio 2022

# Указываем кодировку UTF-8, чтобы логи тестов на русском (если есть) читались корректно
environment:
  JAVA_TOOL_OPTIONS: "-Dfile.encoding=UTF-8"

build_script:
  - gradlew.bat clean test
